#!/bin/bash
#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Manually provision che-gateway when the operator fails to create it.
# Use as a workaround for InstallOrUpdateFailed when the main route expects
# che-gateway but the operator never deployed it.
#
# Prerequisites: che-dashboard deployment, che (server) service, route 'che' exists.
# Creates: OAuthClient (if missing), SA, RBAC, ConfigMaps, Secret, Deployment, Service.
#
# Usage: ./provision-che-gateway-manually.sh --kubeconfig <path> [--namespace <ns>] [--registry <host:port>]
#
# Generated by Cursor AI
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
KUBECONFIG_FILE=""
NAMESPACE="eclipse-che"
REGISTRY=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --kubeconfig) KUBECONFIG_FILE="$2"; shift 2 ;;
        --namespace) NAMESPACE="$2"; shift 2 ;;
        --registry) REGISTRY="$2"; shift 2 ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

if [ -z "$KUBECONFIG_FILE" ] || [ ! -f "$KUBECONFIG_FILE" ]; then
    echo "Usage: $0 --kubeconfig <path> [--namespace eclipse-che] [--registry <host:port>]"
    exit 1
fi

export KUBECONFIG="$KUBECONFIG_FILE"
NS="$NAMESPACE"

# Auto-detect registry from cluster if not provided
if [ -z "$REGISTRY" ]; then
  REGISTRY=$(oc get imagetagmirrorset -o jsonpath='{.items[0].spec.imageTagMirrors[0].mirrors[0]}' 2>/dev/null | sed 's|/.*||' || echo "")
fi
if [ -z "$REGISTRY" ]; then
  REGISTRY=$(oc get imagecontentsourcepolicy -o jsonpath='{.items[0].spec.repositoryDigestMirrors[0].mirrors[0]}' 2>/dev/null | sed 's|/.*||' || echo "")
fi
REGISTRY="${REGISTRY:-virthost.ostest.test.metalkube.org:5000}"

# Auto-detect CHE_HOST from route 'che'
CHE_HOST=$(oc get route che -n "$NS" -o jsonpath='{.spec.host}' 2>/dev/null || true)
CHE_HOST="${CHE_HOST:-eclipse-che.apps.ostest.test.metalkube.org}"

# Detect dashboard service name (eclipse-che-dashboard or che-dashboard)
DASHBOARD_SVC=$(oc get svc -n "$NS" -o name 2>/dev/null | grep -E 'dashboard|eclipse-che-dashboard' | head -1 | sed 's|.*/||' || echo "eclipse-che-dashboard")

echo "Provisioning che-gateway in $NS (CHE_HOST=$CHE_HOST, dashboard=$DASHBOARD_SVC)"

# Note: We always apply ConfigMaps/Service below so routing stays correct even when
# che-gateway pod is already running (configbump will pick up changes).

# Image refs (mirrored to local registry by mirror-images-to-registry.sh)
TRAEFIK_IMAGE="${REGISTRY}/eclipse-che/eclipse/che--traefik:v3.6.7-2c5e029ee3638d3788b4ca7c8ef454baa8f924b91b190b3fd2742bee721ebeea"
CONFIGBUMP_IMAGE="${REGISTRY}/eclipse-che/che-incubator/configbump:next"
OAUTH_PROXY_IMAGE="${REGISTRY}/eclipse-che/openshift/origin-oauth-proxy:4.9"
KUBE_RBAC_PROXY_IMAGE="${REGISTRY}/eclipse-che/openshift/origin-kube-rbac-proxy:4.9"

# 1. OAuth client (cluster-scoped) - required for OpenShift OAuth
OAUTH_CLIENT_NAME="${NS}-client"
OAUTH_SECRET=""
if oc get oauthclient "$OAUTH_CLIENT_NAME" &>/dev/null; then
    OAUTH_SECRET=$(oc get oauthclient "$OAUTH_CLIENT_NAME" -o jsonpath='{.secret}' 2>/dev/null || true)
fi
if [ -z "$OAUTH_SECRET" ]; then
    echo "Creating OAuthClient $OAUTH_CLIENT_NAME..."
    OAUTH_SECRET=$(openssl rand -base64 12 | tr -d '\n')
    if ! oc get oauthclient "$OAUTH_CLIENT_NAME" &>/dev/null; then
        oc create -f - <<EOF
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: ${OAUTH_CLIENT_NAME}
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
secret: ${OAUTH_SECRET}
redirectURIs:
  - https://${CHE_HOST}/oauth/callback
grantMethod: prompt
EOF
    else
        OAUTH_SECRET=$(oc get oauthclient "$OAUTH_CLIENT_NAME" -o jsonpath='{.secret}' 2>/dev/null)
    fi
else
    echo "OAuthClient $OAUTH_CLIENT_NAME exists."
fi

# 2. Cookie secret for oauth-proxy (24-char base64)
COOKIE_SECRET=$(openssl rand -base64 16 | tr -d '\n' | head -c 24)

oc create secret generic che-gateway-oauth-secret -n "$NS" \
    --from-literal=cookie_secret="$COOKIE_SECRET" \
    --dry-run=client -o yaml | oc apply -f -
oc label secret che-gateway-oauth-secret -n "$NS" app=che component=che-gateway --overwrite 2>/dev/null || true

# 3. OAuth proxy ConfigMap
OAUTH_PROXY_CFG="http_address = \":8080\"
https_address = \"\"
provider = \"openshift\"
redirect_url = \"https://${CHE_HOST}/oauth/callback\"
upstreams = [\"http://127.0.0.1:8081/\"]
client_id = \"${OAUTH_CLIENT_NAME}\"
client_secret = \"${OAUTH_SECRET}\"
scope = \"user:full\"
openshift_service_account = \"che-gateway\"
cookie_secret = \"${COOKIE_SECRET}\"
cookie_expire = \"0h24m0s\"
email_domains = \"*\"
cookie_httponly = false
pass_access_token = true
skip_provider_button = false
skip_auth_regex = \"^/\$|/healthz\$|^/dashboard/static/preload|^/dashboard/assets/branding/loader.svg\$\"
"
oc create configmap che-gateway-config-oauth-proxy -n "$NS" \
    --from-literal="oauth-proxy.cfg=$OAUTH_PROXY_CFG" \
    --dry-run=client -o yaml | oc apply -f -
oc label configmap che-gateway-config-oauth-proxy -n "$NS" app=che component=che-gateway --overwrite 2>/dev/null || true

# 4. Kube RBAC proxy ConfigMap
oc create configmap che-gateway-config-kube-rbac-proxy -n "$NS" \
    --from-literal="authorization-config.yaml"='
authorization:
  rewrites:
    byQueryParameter:
      name: "namespace"
  resourceAttributes:
    apiVersion: v1
    apiGroup: workspace.devfile.io
    resource: devworkspaces
    namespace: "{{ .Value }}"
' \
    --dry-run=client -o yaml | oc apply -f -
oc label configmap che-gateway-config-kube-rbac-proxy -n "$NS" app=che component=che-gateway --overwrite 2>/dev/null || true

# 5. Header-rewrite plugin ConfigMap (X-Forwarded-Access-Token -> Authorization: Bearer for OpenShift API)
PLUGIN_DIR="${REPO_ROOT}/manifests/che/helpers/header-rewrite-plugin"
if [ ! -d "$PLUGIN_DIR" ] || [ ! -f "$PLUGIN_DIR/headerRewrite.go" ]; then
    echo "Error: header-rewrite plugin not found at $PLUGIN_DIR (required for OpenShift auth)"
    exit 1
fi
oc create configmap che-gateway-config-header-rewrite-traefik-plugin -n "$NS" \
    --from-file="${PLUGIN_DIR}/headerRewrite.go" \
    --from-file="${PLUGIN_DIR}/.traefik.yml" \
    --from-file="${PLUGIN_DIR}/go.mod" \
    --dry-run=client -o yaml | oc apply -f -
oc label configmap che-gateway-config-header-rewrite-traefik-plugin -n "$NS" app=che component=che-gateway --overwrite 2>/dev/null || true

# 6. Traefik static config (with header-rewrite plugin for OpenShift)
oc create configmap che-gateway-config -n "$NS" \
    --from-literal="traefik.yml"='
entrypoints:
  http:
    address: ":8081"
    forwardedHeaders:
      insecure: true
  sink:
    address: ":8090"
ping:
  entryPoint: "sink"
global:
  checkNewVersion: false
  sendAnonymousUsage: false
providers:
  file:
    directory: "/dynamic-config"
    watch: true
log:
  level: "INFO"
experimental:
  localPlugins:
    header-rewrite:
      moduleName: github.com/che-incubator/header-rewrite-traefik-plugin
' \
    --dry-run=client -o yaml | oc apply -f -
oc label configmap che-gateway-config -n "$NS" app=che component=che-gateway --overwrite 2>/dev/null || true

# 7. Server route (dynamic) - /api, /swagger, /_app -> che-host:8080
# Middleware order: header-rewrite FIRST (X-Forwarded-Access-Token -> Authorization: Bearer), then token-check.
# forwardAuth requires Authorization: Bearer; oauth-proxy sends X-Forwarded-Access-Token.
SERVER_YAML='http:
  routers:
    server:
      rule: "PathPrefix(`/api`) || PathPrefix(`/swagger`) || PathPrefix(`/_app`)"
      service: server
      middlewares: [server-header-rewrite, server-token-check]
      priority: 10
  services:
    server:
      loadBalancer:
        servers:
          - url: "http://che-host:8080"
  middlewares:
    server-header-rewrite:
      plugin:
        header-rewrite:
          from: X-Forwarded-Access-Token
          to: Authorization
          prefix: "Bearer "
    server-token-check:
      forwardAuth:
        address: "https://kubernetes.default.svc/apis/user.openshift.io/v1/users/~"
        trustForwardHeader: true
        tls:
          insecureSkipVerify: true
'
oc create configmap che-gateway-route-server -n "$NS" \
    --from-literal="server.yml"="$SERVER_YAML" \
    --dry-run=client -o yaml | oc apply -f -
oc label configmap che-gateway-route-server -n "$NS" "app=che" "component=che-gateway-config" --overwrite 2>/dev/null || true

# 8. Dashboard route - /, /f, /dashboard -> dashboard
DASHBOARD_YAML="http:
  routers:
    dashboard:
      rule: \"Path(\`/\`) || Path(\`/f\`) || PathPrefix(\`/dashboard/\`)\"
      service: dashboard
      priority: 10
  services:
    dashboard:
      loadBalancer:
        servers:
          - url: \"http://${DASHBOARD_SVC}:8080\"
"
oc create configmap che-gateway-route-dashboard -n "$NS" \
    --from-literal="dashboard.yml"="$DASHBOARD_YAML" \
    --dry-run=client -o yaml | oc apply -f -
oc label configmap che-gateway-route-dashboard -n "$NS" "app=che" "component=che-gateway-config" --overwrite 2>/dev/null || true

# 9. Fallback route (priority 1) - lowest priority catch-all
FALLBACK_YAML='http:
  routers:
    che-no-op:
      rule: "PathPrefix(`/`)"
      service: noop@internal
      middlewares: [che-no-op-headers]
      priority: 1
  middlewares:
    che-no-op-headers:
      headers:
        customResponseHeaders:
          Connection: "close"
'
oc create configmap che-gateway-route-fallback -n "$NS" \
    --from-literal="fallback.yml=$FALLBACK_YAML" \
    --dry-run=client -o yaml | oc apply -f -
oc label configmap che-gateway-route-fallback -n "$NS" "app=che" "component=che-gateway-config" --overwrite 2>/dev/null || true

# 10. ServiceAccount, Role, RoleBinding
oc create serviceaccount che-gateway -n "$NS" 2>/dev/null || true
oc label serviceaccount che-gateway -n "$NS" app=che component=che-gateway --overwrite 2>/dev/null || true

oc apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: che-gateway
  namespace: $NS
  labels:
    app: che
    component: che-gateway
rules:
  - verbs: [watch, get, list]
    apiGroups: [""]
    resources: [configmaps]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: che-gateway
  namespace: $NS
  labels:
    app: che
    component: che-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: che-gateway
subjects:
  - kind: ServiceAccount
    name: che-gateway
    namespace: $NS
EOF

# 11. Deployment
export NAMESPACE="$NS"
export TRAEFIK_IMAGE CONFIGBUMP_IMAGE OAUTH_PROXY_IMAGE KUBE_RBAC_PROXY_IMAGE
envsubst < "${REPO_ROOT}/manifests/che/helpers/che-gateway-deployment.yaml" | oc apply -f -

# 12. Service
oc apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: che-gateway
  namespace: $NS
  labels:
    app: che
    component: che-gateway
spec:
  selector:
    app: che
    component: che-gateway
  ports:
  - name: gateway-http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: gateway-kube-authz
    port: 8089
    targetPort: 8089
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
EOF

# 13. Delete temporary dashboard route if it exists (main route now works via che-gateway)
oc delete route che-dashboard-route -n "$NS" 2>/dev/null || true

echo "Waiting for che-gateway pod..."
oc rollout status deployment/che-gateway -n "$NS" --timeout=120s

echo "Done. che-gateway is running. Main route 'che' should now serve dashboard and API."
