#!/bin/bash
#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Validates air-gap samples in Eclipse Che deployment.
# Checks that the dashboard serves samples at /dashboard/api/airgap-sample
# (list, devfile download, project download).
#
# Uses 'oc exec' into the dashboard pod to curl localhost (no OAuth needed).
# Run after deploy-che-from-bundles.sh with --airgap-samples (default).
#
# Usage: ./test-airgap-samples.sh [options]
#
# Generated by Cursor AI
#
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

CHE_NAMESPACE="eclipse-che"
KUBECONFIG_FILE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --kubeconfig) KUBECONFIG_FILE="$2"; shift 2 ;;
        --namespace|--che-namespace) CHE_NAMESPACE="$2"; shift 2 ;;
        --help)
            echo "Usage: $0 [--kubeconfig <file>] [--namespace eclipse-che]"
            echo ""
            echo "Validates air-gap samples API:"
            echo "  - GET /dashboard/api/airgap-sample (list)"
            echo "  - GET /dashboard/api/airgap-sample/devfile/download?id=<id>"
            echo "  - GET /dashboard/api/airgap-sample/project/download?id=<id>"
            exit 0
            ;;
        *) echo -e "${RED}Unknown: $1${NC}"; exit 1 ;;
    esac
done

if [ -n "$KUBECONFIG_FILE" ]; then
    [ -f "$KUBECONFIG_FILE" ] || { echo -e "${RED}Kubeconfig not found: $KUBECONFIG_FILE${NC}"; exit 1; }
    export KUBECONFIG="$KUBECONFIG_FILE"
fi

NS="$CHE_NAMESPACE"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Testing Air-Gap Samples in Eclipse Che                ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check che-dashboard-airgap Secret exists
if ! oc get secret che-dashboard-airgap -n "$NS" &>/dev/null; then
    echo -e "${RED}Error: Secret che-dashboard-airgap not found in $NS${NC}"
    echo "Air-gap samples were not deployed. Run deploy-che-from-bundles.sh with default (--airgap-samples)."
    exit 1
fi
echo -e "${GREEN}✓ Secret che-dashboard-airgap exists${NC}"

# Find dashboard pod (eclipse-che-dashboard or che-dashboard deployment)
DASHBOARD_POD=$(oc get pods -n "$NS" -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null | grep -E 'eclipse-che-dashboard|che-dashboard' | head -1 || true)
if [ -z "$DASHBOARD_POD" ]; then
    DASHBOARD_POD=$(oc get pods -n "$NS" -l 'app.kubernetes.io/component=che-dashboard' -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
fi
if [ -z "$DASHBOARD_POD" ]; then
    echo -e "${RED}Error: No dashboard pod found in $NS${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Using dashboard pod: $DASHBOARD_POD${NC}"
echo ""

# Exec into dashboard pod and curl localhost (dashboard has curl installed)
echo -e "${YELLOW}Step 1: Testing GET /dashboard/api/airgap-sample (list)...${NC}"
JSON=$(oc exec "$DASHBOARD_POD" -n "$NS" -c dashboard -- curl -sf http://localhost:8080/dashboard/api/airgap-sample 2>/dev/null || \
       oc exec "$DASHBOARD_POD" -n "$NS" -- curl -sf http://localhost:8080/dashboard/api/airgap-sample 2>/dev/null || true)
if [ -z "$JSON" ]; then
    echo -e "${RED}FAIL: No response from airgap-sample list${NC}"
    exit 1
fi
SAMPLE_COUNT=$(echo "$JSON" | grep -o '"id":' | wc -l | tr -d ' ')
if [ "${SAMPLE_COUNT:-0}" -lt 1 ]; then
    echo -e "${RED}FAIL: Expected samples in index, got ${SAMPLE_COUNT:-0}${NC}"
    exit 1
fi
echo -e "${GREEN}PASS: Found $SAMPLE_COUNT sample(s)${NC}"

SAMPLE_ID=$(echo "$JSON" | sed -n 's/.*"id":[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
if [ -z "$SAMPLE_ID" ]; then
    SAMPLE_ID=$(echo "$JSON" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
fi
if [ -z "$SAMPLE_ID" ]; then
    echo -e "${YELLOW}WARN: Could not extract sample id, skipping download tests${NC}"
else
    echo ""
    echo -e "${YELLOW}Step 2: Testing devfile download for sample '$SAMPLE_ID'...${NC}"
    DEVFILE=$(oc exec "$DASHBOARD_POD" -n "$NS" -c dashboard -- curl -sf "http://localhost:8080/dashboard/api/airgap-sample/devfile/download?id=${SAMPLE_ID}" 2>/dev/null | head -5 || \
              oc exec "$DASHBOARD_POD" -n "$NS" -- curl -sf "http://localhost:8080/dashboard/api/airgap-sample/devfile/download?id=${SAMPLE_ID}" 2>/dev/null | head -5 || true)
    if [ -z "$DEVFILE" ] || ! echo "$DEVFILE" | grep -qE 'apiVersion|schemaVersion'; then
        echo -e "${RED}FAIL: Devfile download failed or invalid content${NC}"
        exit 1
    fi
    echo -e "${GREEN}PASS: Devfile download OK${NC}"

    echo ""
    echo -e "${YELLOW}Step 3: Testing project download for sample '$SAMPLE_ID'...${NC}"
    PROJECT_SIZE=$(oc exec "$DASHBOARD_POD" -n "$NS" -c dashboard -- curl -sf -w '%{size_download}' -o /dev/null "http://localhost:8080/dashboard/api/airgap-sample/project/download?id=${SAMPLE_ID}" 2>/dev/null || \
                  oc exec "$DASHBOARD_POD" -n "$NS" -- curl -sf -w '%{size_download}' -o /dev/null "http://localhost:8080/dashboard/api/airgap-sample/project/download?id=${SAMPLE_ID}" 2>/dev/null || echo "0")
    if [ "${PROJECT_SIZE:-0}" -lt 100 ]; then
        echo -e "${YELLOW}WARN: Project download returned small file (size=${PROJECT_SIZE:-0} bytes)${NC}"
    else
        echo -e "${GREEN}PASS: Project download OK (size=${PROJECT_SIZE:-0} bytes)${NC}"
    fi
fi

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Air-Gap Samples Validation Passed                    ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
