#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Node.js devfile for IPv6 testing. Served by devfile-server at /nodejs/devfile.yaml
#
schemaVersion: 2.2.0
metadata:
  name: nodejs-hello-world
  displayName: Node.js Hello World
  description: Simple Node.js application for testing IPv6
  tags: ["NodeJS", "Express", "IPv6"]
  projectType: "nodejs"
components:
  - name: nodejs
    container:
      image: registry.access.redhat.com/ubi8/nodejs-18:latest
      memoryLimit: 1024Mi
      mountSources: true
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - id: install
    exec:
      component: nodejs
      commandLine: npm install
      workingDir: ${PROJECT_SOURCE}
  - id: run
    exec:
      component: nodejs
      commandLine: npm start
      workingDir: ${PROJECT_SOURCE}
