#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Prepare air-gap resources (projects and devfiles) from pre-cloned samples.
# Compatible with devspaces-dashboard approach. Used by prepare-airgap-from-samples.sh.
# Generated by Cursor AI

set -e

init() {
  unset SAMPLES_DIR
  unset SRC_INDEX_JSON_PATH
  unset OUTPUT_DIR

  while [ "$#" -gt 0 ]; do
    case $1 in
      '--src-index-json-path'|'-i') SRC_INDEX_JSON_PATH=$2; shift 1;;
      '--output-dir'|'-o') OUTPUT_DIR=$2; shift 1;;
      '--samples-dir'|'-s') SAMPLES_DIR=$2; shift 1;;
      '--help'|'-h') usage; exit;;
    esac
    shift 1
  done

  if [ -z "${SRC_INDEX_JSON_PATH}" ]; then
    usage
    exit 1
  fi

  if [ -z "${SAMPLES_DIR}" ]; then
    usage
    exit 1
  fi

  if [ -z "${OUTPUT_DIR}" ]; then
    OUTPUT_DIR=$(dirname "${SRC_INDEX_JSON_PATH}")
  fi
}

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --src-index-json-path, -i   Path to the JSON file containing the list of samples
  --output-dir, -o            Directory where the output will be stored
  --samples-dir, -s           Directory with pre-cloned sample repos (one subdir per repo)
  --help, -h                  Show this help message
EOF
}

run() {
  mkdir -p "${OUTPUT_DIR}"
  if [ ! "${SRC_INDEX_JSON_PATH}" = "${OUTPUT_DIR}/index.json" ]; then
    cp "${SRC_INDEX_JSON_PATH}" "${OUTPUT_DIR}/index.json"
  fi

  if [ ! -d "${SAMPLES_DIR}" ]; then
    echo "[ERROR] Samples directory ${SAMPLES_DIR} does not exist." >&2
    exit 1
  fi

  # Process each subdir in SAMPLES_DIR
  for repoName in "${SAMPLES_DIR}"/*/; do
    repoName=$(basename "$repoName")
    [ "$repoName" = "*" ] && continue
    echo "[INFO] Processing sample: ${repoName}"
    if [ -d "${SAMPLES_DIR}/${repoName}" ]; then
      if [ ! -f "${SAMPLES_DIR}/${repoName}/devfile.yaml" ]; then
        echo "[WARN] devfile.yaml not found in ${SAMPLES_DIR}/${repoName}. Skipping." >&2
        continue
      fi
      echo "[INFO] Copying devfile.yaml to ${OUTPUT_DIR}/${repoName}-devfile.yaml"
      cp "${SAMPLES_DIR}/${repoName}/devfile.yaml" "${OUTPUT_DIR}/${repoName}-devfile.yaml"
      echo "[INFO] Zipping ${repoName} into ${OUTPUT_DIR}/${repoName}.zip"
      (cd "$SAMPLES_DIR" && zip --exclude '*.git*' -rq "${repoName}.zip" "$repoName")
      mv "${SAMPLES_DIR}/${repoName}.zip" "${OUTPUT_DIR}/"
    fi
  done

  samplesDirsNum=$(find "$SAMPLES_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')
  if [ "$samplesDirsNum" -eq 0 ]; then
    echo "[ERROR] No samples found in ${SAMPLES_DIR}" >&2
    exit 1
  fi

  samplesNum=$(jq -r '. | length' "$SRC_INDEX_JSON_PATH")
  if [ "$samplesNum" -gt "$samplesDirsNum" ]; then
    echo "[WARN] Index has ${samplesNum} samples but only ${samplesDirsNum} dirs found. Some may be missing." >&2
  fi

  i=0
  while [ $i -lt $samplesNum ]; do
    url=$(jq -r '.['"$i"'].url' "$SRC_INDEX_JSON_PATH")
    if [ "$url" = "null" ] || [ -z "$url" ]; then
      echo "[WARN] Sample ${i} has no URL. Skipping." >&2
      i=$((i + 1))
      continue
    fi
    sampleId=$(jq -r '.['"$i"'].id' "$SRC_INDEX_JSON_PATH")
    if [ "$sampleId" = "null" ] || [ -z "$sampleId" ]; then
      echo "[WARN] Sample ${i} has no ID. Skipping." >&2
      i=$((i + 1))
      continue
    fi
    # Extract repo name: https://github.com/org/repo/tree/branch -> repo
    repoName=$(echo "${url#*://}" | cut -d '/' -f 3)
    archiveFileName="${repoName}.zip"
    devfileFileName="${repoName}-devfile.yaml"
    if [ ! -f "${OUTPUT_DIR}/${archiveFileName}" ]; then
      echo "[WARN] Archive ${archiveFileName} not found. Skipping sample ${sampleId}." >&2
      i=$((i + 1))
      continue
    fi
    if [ ! -f "${OUTPUT_DIR}/${devfileFileName}" ]; then
      echo "[WARN] Devfile ${devfileFileName} not found. Skipping sample ${sampleId}." >&2
      i=$((i + 1))
      continue
    fi
    echo "[INFO] Updating index for sample: ${repoName} (id=${sampleId})"
    devfileLink="CHE_DASHBOARD_INTERNAL_URL/dashboard/api/airgap-sample/devfile/download?id=${sampleId}"
    jq --argjson i "$i" --arg url "$devfileLink" --arg zip "$archiveFileName" --arg devfile "$devfileFileName" \
       '.[$i] |= (.url = $url | .project = {"zip": {"filename": $zip}} | .devfile = {"filename": $devfile})' \
       "${OUTPUT_DIR}/index.json" > "${OUTPUT_DIR}/index.json.tmp"
    mv "${OUTPUT_DIR}/index.json.tmp" "${OUTPUT_DIR}/index.json"

    projectLink="CHE_DASHBOARD_INTERNAL_URL/dashboard/api/airgap-sample/project/download?id=${sampleId}"
    # Inject projects with zip location into devfile (before metadata:)
    if ! grep -q "projects:" "${OUTPUT_DIR}/${devfileFileName}"; then
      # Use perl with | delimiter to avoid escaping slashes in projectLink
      perl -i -0pe "s|metadata:|projects:\n  - name: ${repoName}\n    zip:\n      location: ${projectLink}\nmetadata:|s" \
        "${OUTPUT_DIR}/${devfileFileName}"
    fi
    i=$((i + 1))
  done

  echo "[INFO] Air-gap resources prepared in ${OUTPUT_DIR}"
}

init "$@"
run
