#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Extract container images from air-gap sample devfiles.
# Used by mirror-images-to-registry.sh to mirror images required for air-gap samples.
#
# Usage:
#   ./extract-airgap-sample-images.sh [OPTIONS]
#
# Options:
#   -i, --index PATH    Path to air-gap-samples.json (default: manifests/che/air-gap-samples.json)
#   -d, --airgap-dir    Path to air-gap output dir with *-devfile.yaml (default: build/air-gap)
#   -p, --prepare       Run prepare-airgap-from-samples first if airgap-dir devfiles missing
#   -h, --help          Show this help
#
# Output: One container image reference per line to stdout (e.g. quay.io/..., ghcr.io/...)
#
# Generated by Cursor AI
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST_DIR="${REPO_ROOT}/manifests/che"
SAMPLES_JSON="${MANIFEST_DIR}/air-gap-samples.json"
AIRGAP_DIR="${REPO_ROOT}/build/air-gap"
RUN_PREPARE=false

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Extract container images from air-gap sample devfiles.
Output: one image reference per line (quay.io/..., ghcr.io/..., registry.redhat.io/...).

Options:
  -i, --index PATH     Path to air-gap-samples.json
  -d, --airgap-dir     Path to air-gap output with *-devfile.yaml files
  -p, --prepare        Run prepare-airgap-from-samples if devfiles missing
  -h, --help           Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -i|--index) SAMPLES_JSON="$2"; shift 2 ;;
    -d|--airgap-dir) AIRGAP_DIR="$2"; shift 2 ;;
    -p|--prepare) RUN_PREPARE=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

# Run prepare if requested and devfiles missing
if [ "$RUN_PREPARE" = true ] || [ ! -d "$AIRGAP_DIR" ]; then
  PREPARE_SCRIPT="${SCRIPT_DIR}/prepare-airgap-from-samples.sh"
  if [ -x "$PREPARE_SCRIPT" ] && [ -f "$SAMPLES_JSON" ]; then
    echo "[INFO] Preparing air-gap samples (cloning repos, extracting devfiles)..." >&2
    "$PREPARE_SCRIPT" -i "$SAMPLES_JSON" -o "$AIRGAP_DIR" >&2 || true
  fi
fi

# Extract image: lines from devfiles (components.container.image, components.image)
# Exclude icon base64data and comment-only lines; deduplicate; filter to known registries
tmp=$(mktemp)
trap "rm -f '$tmp'" EXIT

if [ -d "$AIRGAP_DIR" ]; then
  for f in "${AIRGAP_DIR}"/*-devfile.yaml "${AIRGAP_DIR}"/devfile.yaml; do
    [ -f "$f" ] || continue
    grep -E '^\s+image:\s+' "$f" 2>/dev/null | sed -E 's/^[[:space:]]*image:[[:space:]]*//' | sed 's/[[:space:]]*#.*//' >> "$tmp" || true
  done
  if [ -s "$tmp" ]; then
    sort -u "$tmp" | grep -E '^(quay\.io|ghcr\.io|registry\.redhat\.io|registry\.access\.redhat\.com|docker\.io)/' || true
  fi
fi
