#!/bin/bash
#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Fix OAuth login "invalid_request" error caused by redirect_uri mismatch.
# The Che operator may configure oauth-proxy with a different host (e.g. che-eclipse-che)
# than the actual route (e.g. eclipse-che). OpenShift OAuth requires exact redirect_uri match.
#
# This script:
#   1. Gets the actual Che host from the route that serves the gateway
#   2. Patches che-gateway-config-oauth-proxy to use that host for redirect_url
#   3. Ensures OAuthClient has matching redirectURIs
#
# Usage: ./fix-oauth-redirect.sh --kubeconfig <path> [--namespace <ns>]
#
# Generated by Cursor AI
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KUBECONFIG_FILE=""
NAMESPACE="eclipse-che"

while [[ $# -gt 0 ]]; do
    case $1 in
        --kubeconfig) KUBECONFIG_FILE="$2"; shift 2 ;;
        --namespace) NAMESPACE="$2"; shift 2 ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

if [ -z "$KUBECONFIG_FILE" ] || [ ! -f "$KUBECONFIG_FILE" ]; then
    echo "Usage: $0 --kubeconfig <path> [--namespace eclipse-che]"
    exit 1
fi

export KUBECONFIG="$KUBECONFIG_FILE"
NS="$NAMESPACE"

# Get actual Che host from route that serves che-gateway
# Route 'che' typically routes to service 'che-gateway'
CHE_HOST=$(oc get route che -n "$NS" -o jsonpath='{.spec.host}' 2>/dev/null)
[ -z "$CHE_HOST" ] && CHE_HOST=$(oc get route -n "$NS" -o json 2>/dev/null | jq -r '
  .items[] | select(.spec.to.name == "che-gateway") | .spec.host
' 2>/dev/null | head -1)

# Fallback: default for ostest
CHE_HOST="${CHE_HOST:-eclipse-che.apps.ostest.test.metalkube.org}"

echo "Che host from route: $CHE_HOST"

# Get current oauth-proxy config
CFG=$(oc get configmap che-gateway-config-oauth-proxy -n "$NS" -o jsonpath='{.data.oauth-proxy\.cfg}' 2>/dev/null)
if [ -z "$CFG" ]; then
    echo "ConfigMap che-gateway-config-oauth-proxy not found. Run after Che gateway is deployed."
    exit 1
fi

# Check if redirect_url already correct
if echo "$CFG" | grep -q "redirect_url = \"https://${CHE_HOST}/oauth/callback\""; then
    echo "OAuth redirect_url already correct: https://${CHE_HOST}/oauth/callback"
    exit 0
fi

# Patch redirect_url in config
NEW_CFG=$(echo "$CFG" | sed "s|redirect_url = \"https://[^\"]*/oauth/callback\"|redirect_url = \"https://${CHE_HOST}/oauth/callback\"|")
if [ "$CFG" = "$NEW_CFG" ]; then
    echo "Could not update redirect_url in config"
    exit 1
fi

# Apply patched config
oc create configmap che-gateway-config-oauth-proxy -n "$NS" \
    --from-literal="oauth-proxy.cfg=$NEW_CFG" \
    --dry-run=client -o yaml | oc apply -f -

echo "Patched oauth-proxy redirect_url to https://${CHE_HOST}/oauth/callback"

# Ensure OAuthClient has matching redirect URI (operator may have created with different host)
OAUTH_CLIENT_NAME="${NS}-client"
CALLBACK_URI="https://${CHE_HOST}/oauth/callback"
CURRENT_URIS=$(oc get oauthclient "$OAUTH_CLIENT_NAME" -o jsonpath='{.redirectURIs}' 2>/dev/null || echo "[]")
if ! echo "$CURRENT_URIS" | grep -qF "$CALLBACK_URI"; then
    echo "Adding redirect URI to OAuthClient $OAUTH_CLIENT_NAME: $CALLBACK_URI"
    oc patch oauthclient "$OAUTH_CLIENT_NAME" --type=merge -p "{\"redirectURIs\": [\"$CALLBACK_URI\"]}"
else
    echo "OAuthClient $OAUTH_CLIENT_NAME already has redirect URI: $CALLBACK_URI"
fi

# Restart che-gateway to pick up config (configbump watches, but force restart for immediate effect)
echo "Restarting che-gateway to apply OAuth config..."
oc rollout restart deployment/che-gateway -n "$NS" 2>/dev/null || true

echo "Done. OAuth login should work at https://${CHE_HOST}/dashboard/"
