#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Generates a Kubernetes Secret manifest that mounts air-gap samples
# (index.json, devfiles, *.zip) into the Che dashboard.
#
# The Secret mounts at /public/dashboard/devfile-registry/air-gap so
# samples are served via /dashboard/api/airgap-sample/* (devfile and project download).
#
# Replaces CHE_DASHBOARD_INTERNAL_URL with http://che-dashboard.<namespace>.svc:8080
# (matches env var from che-dashboard pod set by Che operator).
#
# Usage:
#   1. Run prepare-airgap-from-samples.sh first (produces build/air-gap/)
#   2. Run this script: ./scripts/generate-airgap-secret-manifest.sh -n eclipse-che
#   3. Apply: kubectl apply -f build/che-dashboard-airgap-secret.yaml -n eclipse-che

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AIRGAP_DIR="${REPO_ROOT}/build/air-gap"
OUTPUT_FILE="${REPO_ROOT}/build/che-dashboard-airgap-secret.yaml"
NAMESPACE="${NAMESPACE:-eclipse-che}"

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Generates che-dashboard-airgap Secret YAML from build/air-gap/.
Run prepare-airgap-from-samples.sh first.

Options:
  -i, --input DIR     Air-gap directory (default: build/air-gap)
  -o, --output FILE   Output YAML file (default: build/che-dashboard-airgap-secret.yaml)
  -n, --namespace NS  Kubernetes namespace (default: eclipse-che)
  -h, --help          Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -i|--input) AIRGAP_DIR="$2"; shift 2 ;;
    -o|--output) OUTPUT_FILE="$2"; shift 2 ;;
    -n|--namespace) NAMESPACE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

if [ ! -d "$AIRGAP_DIR" ]; then
  echo "[ERROR] Air-gap directory not found: $AIRGAP_DIR" >&2
  echo "Run prepare-airgap-from-samples.sh first." >&2
  exit 1
fi

if [ ! -f "${AIRGAP_DIR}/index.json" ]; then
  echo "[ERROR] index.json not found in $AIRGAP_DIR" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

echo "[INFO] Generating Secret from $AIRGAP_DIR -> $OUTPUT_FILE"

# CHE_DASHBOARD_INTERNAL_URL = env from che-dashboard pod (Che operator sets it)
CHE_DASHBOARD_INTERNAL_URL="http://che-dashboard.${NAMESPACE}.svc:8080"
echo "[INFO] Substituting CHE_DASHBOARD_INTERNAL_URL -> $CHE_DASHBOARD_INTERNAL_URL"

# Build secret data (base64-encoded files). Keys = filenames (index.json, *.zip, *-devfile.yaml)
# Substitute CHE_DASHBOARD_INTERNAL_URL in json/yaml files before encoding.
DATA_SECTION=""
for f in "${AIRGAP_DIR}"/*; do
  [ -e "$f" ] || continue
  name=$(basename "$f")
  if [ "${f%.yaml}" != "$f" ] || [ "${f%.json}" != "$f" ]; then
    content=$(sed "s|CHE_DASHBOARD_INTERNAL_URL|${CHE_DASHBOARD_INTERNAL_URL}|g" "$f")
    encoded=$(echo "$content" | base64 | tr -d '\n')
  else
    encoded=$(base64 < "$f" | tr -d '\n')
  fi
  DATA_SECTION="${DATA_SECTION}  ${name}: ${encoded}"$'\n'
done

SECRET_TEMPLATE="${REPO_ROOT}/manifests/che/che-dashboard-airgap-secret-template.yaml"
{
  echo "# Generated by scripts/generate-airgap-secret-manifest.sh"
  echo "# Source: ${AIRGAP_DIR}"
  echo "# Mounts at: /public/dashboard/devfile-registry/air-gap"
  echo "# Dashboard serves samples via: /dashboard/api/airgap-sample/*"
  echo "#"
  sed "s|\${NAMESPACE}|${NAMESPACE}|g" "$SECRET_TEMPLATE"
  echo "data:"
  printf '%s' "$DATA_SECTION"
} > "$OUTPUT_FILE"

echo "[SUCCESS] Secret manifest written to $OUTPUT_FILE"
echo "Apply with: kubectl apply -f $OUTPUT_FILE -n $NAMESPACE"
