#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Prepares air-gap resources from air-gap-samples.json.
# Clones sample repos (or uses --samples-dir if provided) and runs airgap.sh.
# Use for IPv6 / air-gapped clusters where samples must be served from the dashboard.
# Generated by Cursor AI

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST_DIR="${REPO_ROOT}/manifests/che"
SAMPLES_JSON="${MANIFEST_DIR}/air-gap-samples.json"
OUTPUT_DIR="${REPO_ROOT}/build/air-gap"
SAMPLES_DIR=""

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Prepares air-gap resources (index.json, devfiles, *.zip) from air-gap-samples.json.
Output is written to build/air-gap/ by default. Use with deploy script Secret manifest
or copy into a custom che-dashboard image.

Options:
  -i, --index PATH     Path to samples JSON (default: manifests/che/air-gap-samples.json)
  -o, --output PATH    Output directory (default: build/air-gap)
  -s, --samples-dir    Use pre-cloned samples instead of cloning (skips git clone)
  -h, --help           Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -i|--index) SAMPLES_JSON="$2"; shift 2 ;;
    -o|--output) OUTPUT_DIR="$2"; shift 2 ;;
    -s|--samples-dir) SAMPLES_DIR="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

if [ ! -f "$SAMPLES_JSON" ]; then
  echo "[ERROR] Samples JSON not found: $SAMPLES_JSON" >&2
  exit 1
fi

for cmd in jq zip; do
  if ! command -v $cmd &>/dev/null; then
    echo "[ERROR] Required command not found: $cmd" >&2
    exit 1
  fi
done

# Prepare samples: clone or use provided dir
WORK_DIR=$(mktemp -d)
trap "rm -rf $WORK_DIR" EXIT

if [ -n "$SAMPLES_DIR" ]; then
  echo "[INFO] Using pre-cloned samples from: $SAMPLES_DIR"
  if [ ! -d "$SAMPLES_DIR" ]; then
    echo "[ERROR] Samples directory does not exist: $SAMPLES_DIR" >&2
    exit 1
  fi
  SAMPLES_WORK="$SAMPLES_DIR"
else
  echo "[INFO] Cloning samples from GitHub..."
  SAMPLES_WORK="$WORK_DIR/samples"
  mkdir -p "$SAMPLES_WORK"

  count=$(jq -r '. | length' "$SAMPLES_JSON")
  [ "$count" -eq 0 ] && { echo "[ERROR] No samples in $SAMPLES_JSON"; exit 1; }
  for i in $(seq 0 $((count - 1))); do
    url=$(jq -r ".[$i].url" "$SAMPLES_JSON")
    [ "$url" = "null" ] && continue
    # Parse https://github.com/org/repo/tree/branch
    if [[ "$url" =~ https://github\.com/([^/]+)/([^/]+)/tree/(.+) ]]; then
      org="${BASH_REMATCH[1]}"
      repo="${BASH_REMATCH[2]}"
      branch="${BASH_REMATCH[3]}"
      clone_url="https://github.com/${org}/${repo}.git"
    else
      echo "[WARN] Cannot parse URL: $url" >&2
      continue
    fi
    dest="$SAMPLES_WORK/$repo"
    if [ -d "$dest" ]; then
      echo "[INFO] Already cloned: $repo"
    else
      echo "[INFO] Cloning $repo (branch: $branch)..."
      git clone --depth 1 -b "$branch" "$clone_url" "$dest" 2>/dev/null || {
        echo "[WARN] Failed to clone $clone_url" >&2
      }
    fi
  done
fi

# Run airgap script
AIRGAP_SCRIPT="$SCRIPT_DIR/airgap.sh"
if [ ! -x "$AIRGAP_SCRIPT" ]; then
  chmod +x "$AIRGAP_SCRIPT"
fi

"$AIRGAP_SCRIPT" \
  -i "$SAMPLES_JSON" \
  -s "$SAMPLES_WORK" \
  -o "$OUTPUT_DIR"

echo "[SUCCESS] Air-gap resources written to: $OUTPUT_DIR"
ls -la "$OUTPUT_DIR"
